#프로젝트 전체 설정(DB, 앱 등록, 언어 등)
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os # os 모듈 import
from dotenv import load_dotenv # dotenv import

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') # .env 파일에서 SECRET_KEY 값을 읽어옴

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 개발 환경에서는 이렇게 설정
# 뜻 -> "10.0.2.2 주소로 오는 요청 받아줘!"
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.0.2.2',      # 핵심! Android 에뮬레이터용
    '*',             # 개발 중에만 사용 (배포 시 제거)
]
CORS_ALLOW_ALL_ORIGINS = True  # 개발 중에만 사용 (배포 시 제거)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    "corsheaders", # CORS 허용을 위한 앱
    "rest_framework_simplejwt", # JWT 
    "rest_framework",
    'django_filters',

    "users",
    'reviews',
    'community',
    'places',
]

AUTH_USER_MODEL = "users.User"  # '앱이름.모델이름' 형식

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # CORS 미들웨어 추가
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication' # JWT
    ], 
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # 기본적으로 인증이 필요
        # 'rest_framework.permissions.AllowAny' # 개발 중 인증 임시 비활성화
    ], 
}

# JWT 상세 설정
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Access Token 30분
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh Token 7일
    'ROTATE_REFRESH_TOKENS': True,  # Refresh Token 갱신 시 새로 발급
    'BLACKLIST_AFTER_ROTATION': True,  # 기존 Refresh Token 블랙리스트 처리
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Redis 설정 (Refresh Token 저장용)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis 서버 주소
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

CORS_ALLOW_CREDENTIALS = True # 세션 쿠키 전송 허용

CORS_ALLOW_ALL_ORIGINS = True  # 개발 중에만 사용 (배포 시 제거) 

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'test'],  # 테스트용 html 파일 위치
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gilnabi_db',      # 1단계에서 만든 데이터베이스 이름
        'USER': 'postgres',         # PostgreSQL 설치 시 설정한 사용자 이름
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),     # PostgreSQL 설치 시 설정한 비밀번호
        'HOST': 'localhost',        # 보통 localhost 또는 127.0.0.1 입니다.
        'PORT': '5432',             # PostgreSQL 기본 포트
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / 'test',
]

STATICFILES_DIRS = [
    BASE_DIR / "static", # Backend/static 폴더를 지정
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
