#프로젝트 전체 설정(DB, 앱 등록, 언어 등)
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-omg&!wk5hfzu67o2ezo^q=7nl^t2cr&ruwfy=tlyu-31huf#n4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 개발 환경에서는 이렇게 설정
# 뜻 -> "10.0.2.2 주소로 오는 요청 받아줘!"
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.0.2.2',      # 핵심! Android 에뮬레이터용
    '*',             # 개발 중에만 사용 (배포 시 제거)
]
CORS_ALLOW_ALL_ORIGINS = True  # 개발 중에만 사용 (배포 시 제거)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders", # CORS 허용을 위한 앱
    "users"
]

AUTH_USER_MODEL = "users.User"  # '앱이름.모델이름' 형식

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # CORS 미들웨어 추가
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # 개발 중에만 사용 (배포 시 제거)
# 뜻 ->  "모든 출처에서 오는 요청 허용해!"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',   # PostgreSQL 사용
        'NAME': 'gilnabi_db',                          # 데이터베이스 이름
        'USER': 'postgres',                          # DB 사용자
        'PASSWORD': 'qwer1234',                      # DB 비밀번호
        'HOST': 'localhost',                         # DB 서버 주소
        'PORT': '5432',                              # DB 포트
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
