# Generated by Django 5.2.7 on 2025-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                ("building_name", models.CharField(max_length=100)),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("has_ramp", models.BooleanField(default=False)),
                ("wheelchair", models.BooleanField(default=False)),
                ("accessible_toilet", models.BooleanField(default=False)),
                ("has_elevator", models.BooleanField(default=False)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
