# Generated by Django 5.2.7 on 2025-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                ("building_name", models.CharField(max_length=100)),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("has_ramp", models.BooleanField(blank=True, null=True)),
                ("wheelchair", models.BooleanField(blank=True, null=True)),
                ("accessible_toilet", models.BooleanField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
