# Generated by Django 5.2.7 on 2025-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibility',
            name='accessible_toilet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='has_ramp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='wheelchair',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
