# Generated by Django 5.2.7 on 2025-10-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_accessibility_accessible_toilet_and_more'),
        ('places', '0003_enable_pg_trgm'),
    ]

    operations = [
    ]
