# Generated by Django 5.2.7 on 2025-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(default='자유', max_length=20, verbose_name='카테고리'),
        ),
    ]
