# Generated by Django 5.2.8 on 2025-11-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.AddField(
            model_name='review',
            name='place_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=100, verbose_name='장소 ID'),
        ),
        migrations.AddField(
            model_name='review',
            name='place_name',
            field=models.CharField(default='알 수 없는 장소', max_length=200, verbose_name='장소명'),
        ),
    ]
