# Generated by Django 5.2.8 on 2025-11-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reviews', '0002_remove_review_place_review_place_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='place_address',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place_name',
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to='places.accessibility', verbose_name='장소'),
        ),
    ]
