# Generated by Django 5.2.7 on 2025-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="사용자 고유 ID"
                    ),
                ),
                (
                    "social_id",
                    models.CharField(
                        help_text="카카오/구글에서 제공하는 사용자 고유 번호",
                        max_length=255,
                        unique=True,
                        verbose_name="소셜 고유 ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("kakao", "Kakao"), ("google", "Google")],
                        help_text="카카오 또는 구글",
                        verbose_name="로그인 제공자",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="앱에서 표시될 이름",
                        max_length=50,
                        verbose_name="사용자 이름",
                    ),
                ),
                (
                    "profile_image",
                    models.URLField(
                        blank=True,
                        help_text="카카오/구글 프로필 사진 URL",
                        null=True,
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "disability_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("physical", "지체장애"),
                            ("visual", "시각장애"),
                            ("hearing", "청각장애"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_wheelchair", models.BooleanField(default=False, null=True)),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="추가 정보 입력 완료 여부",
                        verbose_name="프로필 완성 여부",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_user_set", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_user_permissions_set",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
