# Generated by Django 5.2.8 on 2025-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='사용자 고유 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('kakao', 'Kakao'), ('google', 'Google')], help_text='카카오 또는 구글', verbose_name='로그인 제공자'),
        ),
    ]
