# Generated by Django 4.2.14 on 2025-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('physical', '지체장애'), ('visual', '시각장애'), ('hearing', '청각장애'), ('other', '기타')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_wheelchair',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
