# Generated by Django 5.2.8 on 2025-11-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('kakao', 'Kakao'), ('google', 'Google')], help_text='카카오 또는 구글', verbose_name='로그인 제공자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='앱에서 표시될 이름', max_length=50, unique=True, verbose_name='사용자 이름'),
        ),
    ]
