# Generated by Django 4.2.14 on 2025-10-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_disability_type_user_has_wheelchair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('physical', '지체장애'), ('visual', '시각장애'), ('hearing', '청각장애'), ('other', '기타')], max_length=20, null=True),
        ),
    ]
