# Generated by Django 4.2.14 on 2025-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_user_disability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('physical', '지체장애'), ('visual', '시각장애'), ('hearing', '청각장애'), ('language', '언어장애')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='추가 정보 입력 완료 여부', verbose_name='프로필 완성 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='사용자가 직접 설정한 닉네임', max_length=50, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, help_text='카카오/구글 프로필 사진 URL', null=True, verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('kakao', 'Kakao'), ('google', 'Google')], help_text='카카오 또는 구글', max_length=20, verbose_name='로그인 제공자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(help_text='카카오/구글에서 제공하는 사용자 고유 번호', max_length=255, unique=True, verbose_name='소셜 고유 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='앱에서 표시될 이름', max_length=50, verbose_name='사용자 이름'),
        ),
    ]
