# Generated by Django 5.2.8 on 2025-11-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='앱에서 표시될 이름', max_length=50, verbose_name='사용자 이름'),
        ),
    ]
