# Generated by Django 4.2.14 on 2025-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_disability_type_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('physical', '지체장애'), ('visual', '시각장애'), ('hearing', '청각장애')], max_length=20, null=True),
        ),
    ]
