# Generated by Django 5.2.8 on 2025-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_disability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('physical', '지체장애'), ('visual', '시각장애'), ('hearing', '청각장애'), ('crutches', '목발')], max_length=20, null=True),
        ),
    ]
